name: leagueoflegends
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  fluttertoast: ^8.0.9
  flutter_easyloading: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: "^0.10.0"

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/tier-icons/

flutter_icons:
  android: true
  ios: true
  image_path: "images/loliconscreen.png"
  remove_alpha_ios: true


